sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with docker"
  - docker build -t gultz/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true gultz/docker-react-app npm run test -- --coverage

after_sucess:
  - echo "Test success"